package emilia.entity.event;

public enum NormativeEventType {
	ACTION,
	ACTION_OBSERVED,
	ACTION_INFORMED,
	COMPLIANCE,
	COMPLIANCE_OBSERVED,
	COMPLIANCE_INFORMED,
	VIOLATION,
	VIOLATION_OBSERVED,
	VIOLATION_INFORMED,
	PUNISHMENT,
	PUNISHMENT_OBSERVED,
	PUNISHMENT_INFORMED,
	SANCTION,
	SANCTION_OBSERVED,
	SANCTION_INFORMED,
	COMPLIANCE_INVOCATION,
	COMPLIANCE_INVOCATION_OBSERVED,
	COMPLIANCE_INVOCATION_INFORMED,
	VIOLATION_INVOCATION,
	VIOLATION_INVOCATION_OBSERVED,
	VIOLATION_INVOCATION_INFORMED
}